language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
- pypy3
env:
- INSTALLATION="python setup.py develop" XDIST=1
- INSTALLATION="pip install ." XDIST=0
before_install:
- mkdir /tmp/dynamodb
- wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest
  | tar xz --directory /tmp/dynamodb
install:
- pip install -r requirements-test.txt
- "$INSTALLATION"
- pip install pytest-dynamodb[tests] coveralls wheel
script:
- py.test -n $XDIST --cov src/pytest_dynamodb tests
- pylama
- pyroma .
after_success:
- coveralls
deploy:
  provider: pypi
  user: thearoom
  password:
    secure: 4LbJos8VHmjNUm4EVlQrFgrw5S/WDE1DrNHMfKc4GUqj5w62tB5S70VltcvsOV8lPkb0zuYC5VbqQbxDhlBDR1NdDB3xAGmAd/N/2pCkR2zlA2DBDGbSMHo9ljvYiXt8CJr7zkCYvARHyjzLnSrXA9kyK0744dtbRHebOvX1O6sH8K+dvtV2Y31PKIrZzIke8qhUCO8uuveOJVsLEG85eeKhl+BYnHAqDTJ+ZAoiXkdbiBzmc8NyRg8eq9U0J1sOJlcvFK+fhdV1nTjDbjk+v7Pn/LF14MxzWVhTi52UittsejGjQ9ddgYNsBLE9D5s2VkQ8LcTlI8X+k/jYIQ2ZhaMQIfTmoDmPrj2c6j4kRxaYpeFwci/LrKWjdYjG0pGHumpstK3OLI0OXC6dahXUAEEmuhhQOmNVenx+jib/dDfYU8Ai5oFQoQBS2Xb/LK+5mguzntyzYWa+UNKjNasSshZE8wsKKOaPgkrMtwmuP1rKXr6gHNprmecCxv+IwxjtYaIKpIb51ofKUKcH7zK/2RdWLqWksZ0kYieW7blHy3efk2d3AwxonQ0ZaCZENQyFv7K6rqDSXNyJ0RrWl4ysq2GD9Pj2SolS97z7+H9io357SblGw9Rn5oDxi1yZ9TeNDvTNtLd9RX8EbZCYBup5Afz1CzBXFkE3RGwu7Mw4xh0=
  on:
    tags: true
    all_branches: true
    repo: ClearcodeHQ/pytest-dynamodb
  distributions: sdist bdist_wheel
