name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@v2.1.2
    with:
      mypy: true
      pipenv: true
      pipenv-install-options: "--skip-lock"
